service: openparkingyyc

plugins:
  - serverless-offline

provider:
  name: aws
  stage: api
  runtime: nodejs12.x
  memorySize: 512
  region: us-west-2

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
